defaults.url=https://sentry.io/
defaults.org=technext96
defaults.project=seavault

# This value is used to authenticate with Sentry when uploading source maps.
# You can find it in your Sentry project settings under Developer Settings > Auth Tokens.
auth.token=YOUR_AUTH_TOKEN_HERE