import { create } from 'zustand';
import { supabase } from '../../../services/supabase';
import { WishlistState, WishlistActions } from '../types/types';
import { Database } from '../../../types/database';
// Import all query functions
import * as queries from '../queries/queries';

export type WishlistStore = WishlistState & WishlistActions;

export const useWishlistStore = create<WishlistStore>((set, get) => ({
  // Initial state
  isLoading: false,
  error: null,

  // Actions
  toggleWishlistItem: async (creatureId: string): Promise<boolean> => {
    try {
      set((state) => ({ ...state, isLoading: true, error: null }));
      
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('No authenticated user');

      // Check if item is already wishlisted
      const isInWishlist = await queries.isCreatureInWishlist(user.id, creatureId);

      if (isInWishlist) {
        // For now, we'll need to find the wishlist item ID to remove it
        // This is a limitation of the current query structure
        const wishlists = await queries.getWishlistByUserId(user.id);
        const wishlistItem = wishlists.find(item => item.creature_id === creatureId);
        
        if (wishlistItem) {
          await queries.removeFromWishlist(wishlistItem.id);
        }
        set((state) => ({ ...state, isLoading: false }));
        return false; // Item removed
      } else {
        // Add to wishlist
        const wishlistData: Database['public']['Tables']['wishlists']['Insert'] = {
          user_id: user.id,
          creature_id: creatureId,
          // Note: id and created_at are auto-generated by the database
        };

        await queries.addToWishlist(wishlistData);
        
        set((state) => ({ ...state, isLoading: false }));
        return true; // Item added
      }
    } catch (error) {
      console.error('Error toggling wishlist item:', error);
      set((state) => ({ ...state, error: 'Failed to toggle wishlist item', isLoading: false }));
      return false;
    }
  },

  addToWishlist: async (wishlistItem: Database['public']['Tables']['wishlists']['Insert']): Promise<Database['public']['Tables']['wishlists']['Row'] | null> => {
    try {
      set((state) => ({ ...state, isLoading: true, error: null }));
      
      const result = await queries.addToWishlist(wishlistItem);
      
      set((state) => ({ ...state, isLoading: false }));
      return result;
    } catch (error) {
      console.error('Error adding to wishlist:', error);
      set((state) => ({ ...state, error: 'Failed to add to wishlist', isLoading: false }));
      return null;
    }
  },

  removeFromWishlist: async (id: string): Promise<void> => {
    try {
      set((state) => ({ ...state, isLoading: true, error: null }));
      
      await queries.removeFromWishlist(id);
      
      set((state) => ({ ...state, isLoading: false }));
    } catch (error) {
      console.error('Error removing from wishlist:', error);
      set((state) => ({ ...state, error: 'Failed to remove from wishlist', isLoading: false }));
      throw error;
    }
  },

  isCreatureInWishlist: async (userId: string, creatureId: string): Promise<boolean> => {
    try {
      return await queries.isCreatureInWishlist(userId, creatureId);
    } catch (error) {
      console.error('Error checking wishlist status:', error);
      return false;
    }
  },

  reset: () => set({
    isLoading: false,
    error: null,
  }),
}));